// ========================
// Update Footer Year
// ========================
(function() {
    const currentYear = new Date().getFullYear();
    const yearElement = document.getElementById('year');
    if (yearElement) {
        yearElement.textContent = currentYear;
    }
})();

// ========================
// Form Details Display & localStorage
// ========================

document.addEventListener('DOMContentLoaded', function() {
    // Get form data from localStorage
    const formDataJSON = localStorage.getItem('contactFormData');
    
    const errorContainer = document.getElementById('errorContainer');
    const successContainer = document.getElementById('successContainer');
    
    if (!formDataJSON) {
        // No data found in localStorage
        errorContainer.style.display = 'block';
        document.getElementById('errorMessage').textContent = 
            '❌ No form submission data found. Please submit the contact form first.';
        successContainer.style.display = 'none';
        return;
    }
    
    try {
        // Parse the form data
        const formData = JSON.parse(formDataJSON);
        
        // Validate that data has required fields
        if (!formData.name || !formData.email || !formData.message) {
            throw new Error('Invalid form data');
        }
        
        // Display success container
        successContainer.style.display = 'block';
        errorContainer.style.display = 'none';
        
        // Populate the form details
        document.getElementById('displayName').textContent = formData.name;
        document.getElementById('displayEmail').textContent = formData.email;
        document.getElementById('displayMessage').textContent = formData.message;
        document.getElementById('displayTimestamp').textContent = formData.timestamp || 'N/A';
        
        // Set up download button
        const downloadBtn = document.getElementById('downloadBtn');
        if (downloadBtn) {
            downloadBtn.addEventListener('click', function() {
                downloadFormDataAsText(formData);
            });
        }
        
    } catch (error) {
        // Error parsing data
        errorContainer.style.display = 'block';
        document.getElementById('errorMessage').textContent = 
            '❌ Error reading form data. The data may have been corrupted. Please submit the form again.';
        successContainer.style.display = 'none';
    }
});

// Function to download form data as text file
function downloadFormDataAsText(formData) {
    const textContent = `
FORM SUBMISSION DETAILS
========================

Name: ${formData.name}
Email: ${formData.email}
Message: ${formData.message}
Submitted At: ${formData.timestamp}

========================
Generated by Piyush Rauniyar's Portfolio
`;

    // Create a blob from the text
    const blob = new Blob([textContent], { type: 'text/plain' });
    
    // Create a temporary URL
    const url = window.URL.createObjectURL(blob);
    
    // Create a temporary anchor element and trigger download
    const link = document.createElement('a');
    link.href = url;
    link.download = `form-submission-${new Date().toISOString().split('T')[0]}.txt`;
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Release the URL
    window.URL.revokeObjectURL(url);
}
